# Generated by Django 4.2.20 on 2025-05-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories_photo/', verbose_name='Изображение')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование товара')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('watched', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('desc', models.TextField(default='Нет описания', verbose_name='Описание товара')),
                ('info', models.TextField(default='Дополнительная информация', verbose_name='Информация о товаре')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('size', models.IntegerField(default=30, verbose_name='Размер в мм')),
                ('color', models.CharField(default='Чёрный', max_length=25, verbose_name='Цвет/Материал')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Галерея товаров',
            },
        ),
    ]
